### ISSUE TITLE
Bind a Positional value

### ISSUE THREAD

**Issue by vendethiel** [CurtTilmes/perl6-dbpg#9]
Hi,

I'm wondering if you considered adding the ability to bind an array, for example `WHERE X IN (@1)`?
I guess I could just take the array elems and generate `$1,$2,$3`, but that seems wasteful.
I could also generate a string and reinterpret it as an array, but I'm afraid of escaping.

Any ideas?

**Comment by CurtTilmes** [comment]
You can bind an array, you just have to use it as an array in your SQL statement.

Instead of `where x in (...)`, say `where x = any($1)` and pass in `@foo` for $1.

If the type is ambiguous, you may need to explicitly tell it what type of array you want it to make:
```
'...where x = any($1::integer[])`, @intlist
```

but I usually don't even need to do that.

You can use the fancier array operations to do other stuff too.

**Comment by vendethiel** [comment]
Hi,

Sorry for not updating the ticket.
This is exactly what’s being done now and it works fine, sorry for not doing better testing before opening the issue.
Since the lib (Badger) integrating DB::Pg even has type information (often), I even generate type ascription.

Thanks!
